import { existsSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { OUTPUT_PATHS, build } from '../scripts/build.ts'
import { readIco } from '../scripts/ico.ts'
import { pngSize } from './png.ts'
import { viewBox } from '../scripts/svg.ts'

const ROOT = new URL('../../', import.meta.url)
const out = build()

describe('pnpm brand:build', () => {
  it('produces exactly the documented outputs', () => {
    expect([...out.keys()].sort()).toEqual([...OUTPUT_PATHS].sort())
    expect(OUTPUT_PATHS).toHaveLength(18)
  })

  it.each([...OUTPUT_PATHS])('%s is committed byte for byte (rebuild and commit after changing a source)', (rel) => {
    const file = new URL(rel, ROOT)
    expect(existsSync(file), `${rel} missing — run pnpm brand:build`).toBe(true)
    expect(readFileSync(file).equals(out.get(rel)!), `${rel} differs from what the sources produce — run pnpm brand:build`).toBe(true)
  })

  it.each([
    ['apps/app/assets/icon.png', 1024, 1024],
    ['apps/app/assets/adaptive-icon.png', 1024, 1024],
    ['apps/app/assets/splash-icon.png', 1024, 736],
    ['apps/app/assets/notification-icon.png', 96, 96],
    ['apps/app/assets/favicon.png', 48, 48],
    ['apps/api/public/favicon-16.png', 16, 16],
    ['apps/api/public/favicon-32.png', 32, 32],
    ['apps/api/public/apple-touch-icon.png', 180, 180],
    ['apps/api/public/og.png', 1200, 630],
  ])('%s is %i×%i', (rel, w, h) => {
    expect(pngSize(out.get(rel)!)).toEqual({ width: w, height: h })
  })

  it('favicon.ico holds the 16, 32 and 48 px PNGs', () => {
    const entries = readIco(out.get('apps/api/public/favicon.ico')!)
    expect(entries.map((e) => [e.width, e.height])).toEqual([[16, 16], [32, 32], [48, 48]])
    for (const e of entries) expect(pngSize(e.png)).toEqual({ width: e.width, height: e.height })
    expect(entries[0]!.png.equals(out.get('apps/api/public/favicon-16.png')!)).toBe(true)
    expect(entries[1]!.png.equals(out.get('apps/api/public/favicon-32.png')!)).toBe(true)
  })

  it('the derived SVGs carry the geometry compose.ts defines', () => {
    const text = (rel: string) => out.get(rel)!.toString('utf8')
    expect(viewBox(text('brand/mark-ink.svg'))).toEqual([42, 102, 1277, 918])
    expect(text('brand/mark-ink.svg')).toContain('fill="#0F1B33"')
    expect(text('brand/mark-paper.svg')).toContain('fill="#FFFFFF"')
    expect(text('brand/mark-lifted.svg')).toContain('fill="#93B4FF"')
    const [hx, hy, hw, hh] = viewBox(text('brand/lockup-horizontal.svg'))
    expect(hx).toBe(0); expect(hy).toBe(-484); expect(hw).toBeCloseTo(5733.32, 1); expect(hh).toBeCloseTo(1517.05, 1)
    const [, , sw, sh] = viewBox(text('brand/lockup-stacked.svg'))
    expect(sw).toBe(3383); expect(sh).toBeCloseTo(3195.58, 1)
    expect(viewBox(text('brand/og-image.svg'))).toEqual([0, 0, 1200, 630])
    expect(viewBox(text('apps/api/public/favicon.svg'))).toEqual([0, 0, 64, 64])
  })

  it('the generated module is a TypeScript constant with the documented header', () => {
    const ts = out.get('packages/contracts/src/brand.ts')!.toString('utf8')
    expect(ts.startsWith('/** GENERATED by `pnpm brand:build`')).toBe(true)
    expect(ts).toContain('export const BRAND = {')
    expect(ts).toContain('} as const\n')
    expect(ts).toContain('export type IconName = keyof typeof BRAND.icons')
  })
})
