/**
 * `pnpm brand:build`. Reads the four sources (tokens.json, mark.svg, wordmark.svg, icons/*.svg), composes
 * the derived SVGs, rasterises with resvg, packs the ICO and writes the tokens module. Idempotent:
 * brand/test/build.test.ts runs build() into memory and fails if any committed output differs.
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { Resvg } from '@resvg/resvg-js'
import { lockupHorizontal, lockupStacked, markSvg, ogImage, tile, wrap } from './compose.ts'
import { packIco } from './ico.ts'
import { allPathData, pathData } from './svg.ts'

const ROOT = new URL('../../', import.meta.url)
const BRAND = new URL('brand/', ROOT)

export const OUTPUT_PATHS = [
  'brand/mark-ink.svg', 'brand/mark-paper.svg', 'brand/mark-lifted.svg',
  'brand/lockup-horizontal.svg', 'brand/lockup-stacked.svg', 'brand/og-image.svg',
  'apps/app/assets/icon.png', 'apps/app/assets/adaptive-icon.png', 'apps/app/assets/splash-icon.png',
  'apps/app/assets/notification-icon.png', 'apps/app/assets/favicon.png',
  'apps/api/public/favicon.svg', 'apps/api/public/favicon-16.png', 'apps/api/public/favicon-32.png',
  'apps/api/public/favicon.ico', 'apps/api/public/apple-touch-icon.png', 'apps/api/public/og.png',
  'packages/contracts/src/brand.ts',
] as const
export type OutputPath = (typeof OUTPUT_PATHS)[number]

interface Tokens {
  light: Record<string, string>
  dark: Record<string, string>
  mark: { raster: { appIconHeight: number; adaptiveIconHeight: number; splashImageWidth: number; notificationWidth: number; faviconWidth: number; ogLockupWidth: number } }
  [key: string]: unknown
}

const read = (rel: string) => readFileSync(new URL(rel, BRAND), 'utf8')
/** Wraps svg.ts's pathData so a failure names the file it came from. */
const readPath = (rel: string): string => {
  try {
    return pathData(read(rel))
  } catch (e) {
    throw new Error(`${rel}: ${(e as Error).message}`)
  }
}

/** No SVG here contains text, so no fonts are loaded — the render is the same on every machine. */
function png(svg: string, width: number): Buffer {
  return Buffer.from(new Resvg(svg, { fitTo: { mode: 'width', value: width }, font: { loadSystemFonts: false } }).render().asPng())
}

function brandModule(tokens: Tokens, mark: string, word: string, icons: Record<string, string[]>): string {
  const l = lockupHorizontal(mark, word, '#000', '#000')
  const value = {
    ...tokens,
    paths: {
      mark: { viewBox: '42 102 1277 918', d: mark },
      wordmark: { viewBox: '42 100 3383 920', d: word },
      lockupHorizontal: { viewBox: l.viewBox, width: Number(l.width.toFixed(4)), height: Number(l.height.toFixed(4)), markTransform: l.markTransform, wordmarkTransform: l.wordmarkTransform },
    },
    icons,
  }
  return '/** GENERATED by `pnpm brand:build` from brand/tokens.json, brand/mark.svg, brand/wordmark.svg and brand/icons/ — do not edit; change a source and rebuild. */\n'
    + `export const BRAND = ${JSON.stringify(value, null, 2)} as const\n\n`
    + 'export type Brand = typeof BRAND\n'
    + 'export type IconName = keyof typeof BRAND.icons\n'
}

export function build(): Map<string, Buffer> {
  const tokens = JSON.parse(read('tokens.json')) as Tokens
  const mark = readPath('mark.svg')
  const word = readPath('wordmark.svg')
  const icons = Object.fromEntries(
    readdirSync(new URL('icons/', BRAND)).filter((f) => f.endsWith('.svg')).sort()
      .map((f) => [f.slice(0, -4), allPathData(read(`icons/${f}`))]),
  )
  const { light: L, dark: D, mark: { raster: R } } = tokens
  const out = new Map<string, Buffer>()
  const put = (rel: OutputPath, data: string | Buffer) => { out.set(rel, typeof data === 'string' ? Buffer.from(data, 'utf8') : data) }

  put('brand/mark-ink.svg', markSvg(mark, L.ink!))
  put('brand/mark-paper.svg', markSvg(mark, L.paper!))
  put('brand/mark-lifted.svg', markSvg(mark, D.lifted!))
  put('brand/lockup-horizontal.svg', wrap(lockupHorizontal(mark, word, L.primary!, L.ink!)))
  put('brand/lockup-stacked.svg', wrap(lockupStacked(mark, word, L.primary!, L.ink!)))
  const og = wrap(ogImage(mark, word, D.night!, D.lifted!, D.paperOnNight!, R.ogLockupWidth))
  put('brand/og-image.svg', og)

  put('apps/app/assets/icon.png', png(wrap(tile(mark, D.lifted!, 1024, { height: R.appIconHeight }, D.night!)), 1024))
  put('apps/app/assets/adaptive-icon.png', png(wrap(tile(mark, D.lifted!, 1024, { height: R.adaptiveIconHeight }, null)), 1024))
  put('apps/app/assets/splash-icon.png', png(markSvg(mark, D.lifted!), 1024))
  put('apps/app/assets/notification-icon.png', png(wrap(tile(mark, '#FFFFFF', 96, { width: R.notificationWidth }, null)), 96))
  put('apps/app/assets/favicon.png', png(wrap(tile(mark, L.primary!, 48, { width: R.faviconWidth }, null)), 48))

  const favicon = wrap(tile(mark, L.primary!, 64, { width: R.faviconWidth }, null))
  put('apps/api/public/favicon.svg', favicon)
  const f16 = png(favicon, 16), f32 = png(favicon, 32), f48 = png(favicon, 48)
  put('apps/api/public/favicon-16.png', f16)
  put('apps/api/public/favicon-32.png', f32)
  put('apps/api/public/favicon.ico', packIco([{ size: 16, png: f16 }, { size: 32, png: f32 }, { size: 48, png: f48 }]))
  put('apps/api/public/apple-touch-icon.png', png(wrap(tile(mark, D.lifted!, 180, { height: R.appIconHeight }, D.night!)), 180))
  put('apps/api/public/og.png', png(og, 1200))

  put('packages/contracts/src/brand.ts', brandModule(tokens, mark, word, icons))
  return out
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  for (const [rel, data] of build()) {
    const file = fileURLToPath(new URL(rel, ROOT))
    mkdirSync(dirname(file), { recursive: true })
    writeFileSync(file, data)
    console.log(`${rel}  ${data.length} bytes`)
  }
}
