import { sql } from 'drizzle-orm'
import { boolean, check, customType, index, integer, jsonb, pgTable, text, timestamp, uniqueIndex, uuid, vector } from 'drizzle-orm/pg-core'
import { user } from './auth.ts'
import { createdAt, emptyTextArray, id, orgId, tenantPolicies, updatedAt } from './helpers.ts'

/** Postgres full-text vector; drizzle has no built-in, and the column is generated, so it is never written from code. */
const tsvector = customType<{ data: string }>({ dataType: () => 'tsvector' })

/** One uploaded file, one pasted text, or one crawl of a site (spec §Data model → Knowledge & learning). */
export const knowledgeSources = pgTable('knowledge_sources', {
  id: id(),
  orgId: orgId(),
  kind: text('kind').notNull(),                       // upload | paste | crawl (CHECK)
  status: text('status').notNull().default('queued'), // queued | processing | ready | failed (CHECK)
  title: text('title').notNull(),
  storageKey: text('storage_key'),                    // orgs/<orgId>/uploads/<sourceId>/<fileName>
  mime: text('mime'),
  byteSize: integer('byte_size'),
  url: text('url'),                                   // the crawl's start URL
  crawlConfig: jsonb('crawl_config').notNull().default(sql`'{}'::jsonb`),   // { maxPages, progress: { fetched, ingested, skipped, frontier? } }
  pastedText: text('pasted_text'),
  contentHash: text('content_hash'),
  documentCount: integer('document_count').notNull().default(0),
  chunkCount: integer('chunk_count').notNull().default(0),
  failureReason: text('failure_reason'),              // contracts KNOWLEDGE_FAILURE_REASONS
  failureDetail: text('failure_detail'),
  createdBy: uuid('created_by').references(() => user.id, { onDelete: 'set null' }),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
  completedAt: timestamp('completed_at', { withTimezone: true }),
}, (t) => [
  index('knowledge_sources_org_status_idx').on(t.orgId, t.status),
  index('knowledge_sources_org_created_idx').on(t.orgId, t.createdAt.desc()),
  ...tenantPolicies(t.orgId, 'knowledge_sources'),
])

/** One parsed unit under a source: the file itself, the paste, or one crawled page. */
export const knowledgeDocuments = pgTable('knowledge_documents', {
  id: id(),
  orgId: orgId(),
  sourceId: uuid('source_id').notNull().references(() => knowledgeSources.id, { onDelete: 'cascade' }),
  uri: text('uri').notNull(),                         // the page URL, `upload:<key>` or `paste:<sourceId>`
  title: text('title'),
  contentHash: text('content_hash').notNull(),
  version: integer('version').notNull().default(1),
  chunkCount: integer('chunk_count').notNull().default(0),
  embeddedCount: integer('embedded_count').notNull().default(0),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
}, (t) => [
  uniqueIndex('knowledge_documents_source_uri_uidx').on(t.sourceId, t.uri),
  index('knowledge_documents_org_source_idx').on(t.orgId, t.sourceId),
  ...tenantPolicies(t.orgId, 'knowledge_documents'),
])

/** The retrieval unit. `embedding` is null until knowledge.embed-batch fills it; `tsv` is generated by Postgres. */
export const knowledgeChunks = pgTable('knowledge_chunks', {
  id: id(),
  orgId: orgId(),
  documentId: uuid('document_id').notNull().references(() => knowledgeDocuments.id, { onDelete: 'cascade' }),
  ordinal: integer('ordinal').notNull(),
  headingPath: text('heading_path').array().notNull().default(emptyTextArray()),
  content: text('content').notNull(),
  tokenCount: integer('token_count').notNull(),
  embedding: vector('embedding', { dimensions: 1024 }),
  embeddingModel: text('embedding_model'),
  embeddingVersion: integer('embedding_version'),
  tsv: tsvector('tsv').generatedAlwaysAs(sql`to_tsvector('simple', content)`),
  injectionFlagged: boolean('injection_flagged').notNull().default(false),
  injectionReason: text('injection_reason'),
  createdAt: createdAt(),
}, (t) => [
  uniqueIndex('knowledge_chunks_document_ordinal_uidx').on(t.documentId, t.ordinal),
  index('knowledge_chunks_org_document_idx').on(t.orgId, t.documentId),   // the exact-scan path EXPLAIN must take (spec: no global HNSW)
  index('knowledge_chunks_tsv_idx').using('gin', t.tsv),
  check('knowledge_chunks_content_check', sql`char_length(${t.content}) <= 3000`),
  ...tenantPolicies(t.orgId, 'knowledge_chunks'),
])
